# Generated by Django 5.1.1 on 2024-11-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookBindingRequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookBindRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='LaminationPersonnelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaminationRequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LaminationRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signatories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookBindingPersonnelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(default='pending', max_length=10)),
                ('pdf', models.FileField(null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('book_binding_request_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookbindingrequestdetails')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='BookBindQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('book_bind_personnel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookbindingpersonnelrequest')),
            ],
        ),
        migrations.AddField(
            model_name='bookbindingrequestdetails',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookbindrequesttype'),
        ),
        migrations.CreateModel(
            name='BookBindingStudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('pdf', models.FileField(null=True, upload_to='uploads/')),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('book_binding_request_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bookbindingrequestdetails')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='LaminationPersonnelQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('lamination_personnel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laminationpersonnelrequest')),
            ],
        ),
        migrations.AddField(
            model_name='laminationpersonnelrequest',
            name='lamination_request_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laminationrequestdetails'),
        ),
        migrations.AddField(
            model_name='laminationrequestdetails',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laminationrequesttype'),
        ),
        migrations.CreateModel(
            name='LaminationStudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('pdf', models.FileField(null=True, upload_to='uploads/')),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('lamination_request_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laminationrequestdetails')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='laminationrequestdetails',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.papertype'),
        ),
        migrations.AddField(
            model_name='bookbindingrequestdetails',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.papertype'),
        ),
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_order_number', models.IntegerField(default=5)),
                ('documentcodenumber', models.CharField(default='FM-USTP-PP-07', max_length=50)),
                ('revnumber', models.IntegerField(default=0)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('pagenumber', models.CharField(default='1 of 1', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(default='Payment Slip', max_length=10, null=True)),
                ('paid_status', models.CharField(default='Unpaid', max_length=10)),
                ('description', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('unitcost', models.IntegerField(null=True)),
                ('totalcost', models.IntegerField(null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('book_bind_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bookbindingstudentrequest')),
                ('lamination_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.laminationstudentrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LaminationStudentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('lamination_student_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paymentslip')),
            ],
        ),
        migrations.CreateModel(
            name='BookBindStudentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('book_bind_student_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paymentslip')),
            ],
        ),
        migrations.CreateModel(
            name='PrintingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onHand', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(editable=False, max_length=50)),
                ('paper_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.papertype')),
            ],
        ),
        migrations.CreateModel(
            name='PrintRequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplex', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.papertype')),
                ('printing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printingtype')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requesttype')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelPrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(null=True, upload_to='uploads/')),
                ('request_status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('urgent', models.BooleanField(blank=True, default=False)),
                ('print_request_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printrequestdetails')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='QueueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('personnel_print_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnelprintrequest')),
            ],
        ),
        migrations.AddField(
            model_name='laminationpersonnelrequest',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicetype'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_order_number', models.IntegerField(default=5)),
                ('documentcodenumber', models.CharField(default='FM-USTP-PP-05', max_length=50)),
                ('revnumber', models.IntegerField(default=0)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('pagenumber', models.CharField(default='1 of 2', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(max_length=10)),
                ('paid_status', models.CharField(default='Unpaid', max_length=10)),
                ('description', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('unitcost', models.IntegerField(null=True)),
                ('totalcost', models.IntegerField(null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('book_bind_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bookbindingpersonnelrequest')),
                ('lamination_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.laminationpersonnelrequest')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personnelprintrequest')),
                ('signatories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.signatories')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPrintForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('pdf', models.FileField(null=True, upload_to='uploads/')),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('print_request_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printrequestdetails')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicetype')),
            ],
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.studentprintform'),
        ),
        migrations.CreateModel(
            name='StudentQueueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('student_print_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paymentslip')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(default='Personnel', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=100, null=True)),
                ('barangay', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('student_id', models.IntegerField(null=True)),
                ('code', models.IntegerField(null=True)),
                ('account_status', models.CharField(default='Pending', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
        migrations.AddField(
            model_name='personnelprintrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='laminationpersonnelrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='bookbindingpersonnelrequest',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
