# Generated by Django 5.1.1 on 2024-11-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type_name', models.CharField(choices=[('print', 'Printing'), ('bookbind', 'Book-Binding'), ('laminate', 'Lamination')], default='Printing', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signatories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPrintForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrintingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onHand', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(editable=False, max_length=50)),
                ('paper_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.papertype')),
            ],
        ),
        migrations.CreateModel(
            name='PrintRequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplex', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.papertype')),
                ('printing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printingtype')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelPrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('pdf', models.FileField(null=True, upload_to='uploads/')),
                ('request_status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
                ('print_request_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.printrequestdetails')),
            ],
        ),
        migrations.CreateModel(
            name='QueueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('personnel_print_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnelprintrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('duplex', models.BooleanField()),
                ('customer_request_status', models.CharField(max_length=100, null=True)),
                ('personnel_request_status', models.CharField(max_length=100, null=True)),
                ('paper_size', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.papertype')),
                ('request_type_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.printingtype')),
                ('student_print_form', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.studentprintform')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('queue_status', models.CharField(default='pending', max_length=100)),
                ('request', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.request')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_order_number', models.IntegerField(default=5)),
                ('documentcodenumber', models.CharField(default='FM-USTP-PP-05', max_length=50)),
                ('revnumber', models.IntegerField(default=0)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('pagenumber', models.CharField(default='1 of 2', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(default='Billing', max_length=10, null=True)),
                ('paid_status', models.CharField(default='Unpaid', max_length=10)),
                ('description', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('unitcost', models.IntegerField(null=True)),
                ('totalcost', models.IntegerField(null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnelprintrequest')),
                ('signatories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.signatories')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateQueueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_status', models.CharField(default='Pending', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('personnel_print_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnelprintrequest')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirmpassword', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
    ]
