# Generated by Django 5.1.1 on 2025-02-11 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printinginventory',
            name='paper_type',
        ),
        migrations.AddField(
            model_name='printinginventory',
            name='inventory_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='balance_per_card',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
