# Generated by Django 5.1.1 on 2024-12-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbindingpersonnelrequest',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookbindingstudentrequest',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='laminationpersonnelrequest',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='laminationstudentrequest',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
