# Generated by Django 5.1.1 on 2024-12-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelprintrequest',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprintform',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
