# Generated by Django 5.1.1 on 2024-12-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personnelprintrequest_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinginventory',
            name='onHand',
            field=models.IntegerField(default=0),
        ),
    ]
