# Generated by Django 5.1.1 on 2025-02-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_printinginventory_paper_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printinginventory',
            name='paper_type',
        ),
    ]
