# Generated by Django 5.1.1 on 2024-11-24 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_laminationrequesttype_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laminationpersonnelrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='laminationpersonnelrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='laminationpersonnelrequest',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='laminationpersonnelrequest',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='laminationpersonnelrequest',
            name='position',
        ),
        migrations.AddField(
            model_name='laminationpersonnelrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
            preserve_default=False,
        ),
    ]
