# Generated by Django 5.1.1 on 2024-11-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_laminationpersonnelrequest_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminationpersonnelrequest',
            name='service_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.servicetype'),
            preserve_default=False,
        ),
    ]
