# Generated by Django 5.1.1 on 2025-02-11 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_printinginventory_paper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinprocessinventory',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem'),
        ),
    ]
