# Generated by Django 5.1.1 on 2024-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_printinginventory_onhand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinginventory',
            name='onHand',
            field=models.IntegerField(null=True),
        ),
    ]
