# Generated by Django 5.1.1 on 2025-02-11 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_workinprocessinventory_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinprocessinventory',
            name='inventory_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem'),
        ),
    ]
