# Generated by Django 5.1.1 on 2024-11-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bill_lamination_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminationpersonnelrequest',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
