# Generated by Django 5.1.1 on 2024-11-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_laminationpersonnelrequest_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminationstudentrequest',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='request_type',
            field=models.CharField(choices=[('Printing', 'Printing'), ('Book Binding', 'Book Binding'), ('Lamination', 'Lamination')], max_length=20),
        ),
    ]
