# Generated by Django 5.1.1 on 2024-11-24 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_laminationstudentrequest_page_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laminationstudentrequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department'),
        ),
    ]
