# Generated by Django 5.1.1 on 2025-02-12 01:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stockcard_raw_materials_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinprocessinventory',
            old_name='stock_quantity',
            new_name='balance_per_card',
        ),
        migrations.AddField(
            model_name='workinprocessinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workinprocessinventory',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventoryitem'),
        ),
    ]
