# Generated by Django 5.1.1 on 2024-11-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_laminationstudentrequest_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='lamination_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.laminationstudentrequest'),
        ),
    ]
