# Generated by Django 5.1.1 on 2025-02-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_stock_quantity_workinprocessinventory_balance_per_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='onhand_per_count',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sheets_per_ream',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
