# Generated by Django 5.1.1 on 2024-11-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_bookbindingpersonnelrequest_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laminationstudentqueue',
            name='lamination_student_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paymentslip'),
        ),
    ]
