# Generated by Django 5.1.1 on 2025-02-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_workinprocessfifo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinprocessfifo',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='workinprocessfifo',
            name='work_in_process',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='api.workinprocessinventory'),
            preserve_default=False,
        ),
    ]
