# Generated by Django 5.1.1 on 2024-11-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_laminationstudentqueue_lamination_student_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminationstudentrequest',
            name='service_type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.servicetype'),
            preserve_default=False,
        ),
    ]
