# Generated by Django 5.1.1 on 2024-11-26 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_laminationstudentrequest_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Printing', 'Printing'), ('Book Binding', 'Book Binding'), ('Lamination', 'Lamination')], max_length=20)),
                ('job_order_number', models.IntegerField(default=5)),
                ('documentcodenumber', models.CharField(default='FM-USTP-PP-05', max_length=50)),
                ('revnumber', models.IntegerField(default=0)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('pagenumber', models.CharField(default='1 of 2', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(default='Job Order', max_length=10, null=True)),
                ('paid_status', models.CharField(default='Unpaid', max_length=10)),
                ('description', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(default='pcs', max_length=10)),
                ('unitcost', models.IntegerField(null=True)),
                ('totalcost', models.IntegerField(null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('book_bind_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bookbindingpersonnelrequest')),
                ('lamination_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.laminationpersonnelrequest')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personnelprintrequest')),
                ('signatories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.signatories')),
            ],
        ),
    ]
