# Generated by Django 5.1.1 on 2025-02-13 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_reportofmaterialsandmaterialsissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportofmaterialsandmaterialsissued',
            name='quantity_issued',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportofmaterialsandmaterialsissued',
            name='stock_card',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='api.stockcard'),
            preserve_default=False,
        ),
    ]
