# Generated by Django 5.1.1 on 2024-11-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_joborder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='request_type',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='request_type',
        ),
    ]
