# Generated by Django 5.1.1 on 2025-02-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_reportofmaterialsandmaterialsissued_quantity_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportofmaterialsandmaterialsissued',
            name='stock_card',
        ),
    ]
