# Generated by Django 5.1.1 on 2025-02-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_reportofmaterialsandmaterialsissued_stock_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inktype',
            old_name='ink_type_name',
            new_name='ink_color',
        ),
        migrations.RemoveField(
            model_name='inktype',
            name='price',
        ),
    ]
