# Generated by Django 5.1.1 on 2025-02-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_ink_type_name_inktype_ink_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='ink_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.inktype'),
        ),
    ]
