# Generated by Django 5.1.1 on 2025-02-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_inventoryitem_ink_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TonerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toner_color', models.CharField(max_length=100)),
            ],
        ),
    ]
