# Generated by Django 5.1.1 on 2025-02-14 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_tonertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='toner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tonertype'),
        ),
    ]
