# Generated by Django 5.1.1 on 2025-02-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_inventoryitem_toner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingBinderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_binder_size', models.CharField(max_length=100)),
            ],
        ),
    ]
