# Generated by Django 5.1.1 on 2025-02-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_inventoryitem_ring_binder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='ring_binder_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
