# Generated by Django 5.1.1 on 2025-02-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_inventoryitem_ring_binder_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='ring_binder_count',
        ),
    ]
