# Generated by Django 5.1.1 on 2025-02-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_inventoryitem_ring_binder_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinprocessinventory',
            name='sheets_per_ream',
            field=models.IntegerField(default=0),
        ),
    ]
