# Generated by Django 5.1.1 on 2025-02-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_workinprocessfifo_sheets_per_ream'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinprocessfifo',
            name='transferred_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workinprocessfifo',
            name='transferred_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
