# Generated by Django 5.1.1 on 2025-02-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_laminationfilmsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='lamination_film_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.laminationfilmsize'),
        ),
    ]
