# Generated by Django 5.1.1 on 2025-03-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_inventoryitem_lamination_film_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='lamination_film_size',
        ),
        migrations.RemoveField(
            model_name='printrequestdetails',
            name='paper_type',
        ),
        migrations.AddField(
            model_name='printrequestdetails',
            name='work_in_process_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workinprocessinventory'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('Ink', 'Ink'), ('Paper', 'Paper'), ('Toner', 'Toner'), ('Battery', 'Battery'), ('Office Storage', 'Office Storage & Organization'), ('Binding', 'Binding'), ('Laminating', 'Laminating'), ('Film', 'Film'), ('ID Card', 'ID Card')], max_length=50),
        ),
        migrations.DeleteModel(
            name='LaminationFilmSize',
        ),
    ]
