# Generated by Django 5.1.1 on 2025-03-04 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_inventoryitem_lamination_film_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookbindingrequestdetails',
            name='paper_type',
        ),
        migrations.AddField(
            model_name='bookbindingrequestdetails',
            name='ring_binder_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ringbindertype'),
        ),
        migrations.AddField(
            model_name='bookbindingrequestdetails',
            name='work_in_process_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workinprocessinventory'),
        ),
    ]
