# Generated by Django 5.1.1 on 2025-03-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_bookbindingrequestdetails_paper_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookbindingrequestdetails',
            name='ring_binder_type',
        ),
    ]
