# Generated by Django 5.1.1 on 2025-03-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_bookbindingrequestdetails_ring_binder_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookbindingrequestdetails',
            name='work_in_process_inventory',
        ),
        migrations.AddField(
            model_name='bookbindingrequestdetails',
            name='work_in_process_inventory',
            field=models.ManyToManyField(blank=True, null=True, to='api.workinprocessinventory'),
        ),
    ]
