# Generated by Django 5.1.1 on 2025-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_bookbindingrequestdetails_work_in_process_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laminationrequestdetails',
            name='paper_type',
        ),
        migrations.AddField(
            model_name='laminationrequestdetails',
            name='work_in_process_inventory',
            field=models.ManyToManyField(blank=True, null=True, to='api.workinprocessinventory'),
        ),
        migrations.AddField(
            model_name='rawmaterialsinventory',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workinprocessinventory',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
